const express = require('express');
// const authnticateUser = require('../MiddleWares/auth');
// const moneyController = require('../Controllers/moneyController');
const expenseRoutes = express.Router();
// expenseRoutes.get('/MainHome', moneyController.getExpenseMainHomePage);
// expenseRoutes.get('/expenseMain', moneyController.getExpenseMainPage);
// expenseRoutes.post('/post-expense', authnticateUser, moneyController.addExpense);
// expenseRoutes.get('/viewExpenses', moneyController.getExpensesViewPage);
// expenseRoutes.get('/viewExpensesData', authnticateUser, moneyController.getExpensesData);
// expenseRoutes.post('/deleteExpensedata', authnticateUser, moneyController.deleteExpenseData);
// expenseRoutes.post('/update-expense', authnticateUser, moneyController.updateExpense);
// expenseRoutes.get('/leaderBoardPage', moneyController.getLeaderBoardPage);
// expenseRoutes.get('/viewLeaderBoardData', moneyController.getLeaderBoardData);
// expenseRoutes.get('/viewMonetaryData', moneyController.getViewMonetaryPage);
// expenseRoutes.get('/viewYearlyExpensesData', authnticateUser, moneyController.getYearlyExpensesData);
// expenseRoutes.post('/download', authnticateUser, moneyController.downloadExpense);
// expenseRoutes.get('/getDownloadUrl', authnticateUser, moneyController.getDownloadUrl);
// expenseRoutes.get('/viewReportExpensesData', authnticateUser, moneyController.viewReportExpensesData);
// expenseRoutes.get('/viewExpenseGraph', moneyController.getExpenseGraph);
module.exports = expenseRoutes;